version: '3'
services:
  app: 
    container_name: audio-player-backend
    restart: always
    env_file: .env.docker
    build: .
    volumes:
      - .:/src
      - /src/node_modules
    ports: 
      - "3000:3000"
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"